package com.thecocktailapp.presentation.utils

const val DETAIL_TOOLBAR = "DETAIL_TOOLBAR"
const val FAVORITE_TOOLBAR = "FAVORITE_TOOLBAR"
const val HOME_BUTTON_SEE_DETAIL = "HOME_BUTTON_SEE_DETAIL"
const val HOME_TOOLBAR = "HOME_TOOLBAR"
const val HOME_MENU_BUTTON = "HOME_MENU_BUTTON"
const val HOME_RECYCLER_VIEW = "HOME_RECYCLER_VIEW"
const val MENU_NAVIGATION_ITEM = "MENU_NAVIGATION_ITEM"
const val PROGRESS_DIALOG_LOTTIE = "PROGRESS_DIALOG_LOTTIE"
const val SPLASH_CANCEL_BUTTON = "SPLASH_CANCEL_BUTTON"
const val SPLASH_SEE_BUTTON = "SPLASH_SEE_BUTTON"